import json
from pathlib import Path


SOURCE_FILES = [
    Path("/Users/jeff/culinary-mind/raw/architect/gemini-bridge/outbox/p107-split/phn_seed_input_part1.json"),
    Path("/Users/jeff/culinary-mind/raw/architect/gemini-bridge/outbox/p107-split/phn_seed_input_part2.json"),
    Path("/Users/jeff/culinary-mind/raw/architect/gemini-bridge/outbox/p107-split/phn_seed_input_part3.json"),
]

OUTPUT_FILE = Path("/Users/jeff/Documents/New project/tmp/p107_phn_seed_output.json")


def load_sources():
    domains = {}
    mother_formulas = []
    for path in SOURCE_FILES:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
        domains.update(data.get("domains", {}))
        mother_formulas.extend(data.get("mother_formulas", []))
    return domains, {mf["id"] for mf in mother_formulas}


DOMAINS, VALID_MF_IDS = load_sources()


def s(domain: str, index_1_based: int) -> str:
    return DOMAINS[domain][index_1_based - 1]["statement"]


def phn(
    phn_id,
    name_en,
    name_zh,
    domain,
    cross_domains,
    definition,
    observable_cues,
    key_parameters,
    related_mf_ids,
    refs,
    granularity_note,
):
    return {
        "phn_id": phn_id,
        "name_en": name_en,
        "name_zh": name_zh,
        "domain": domain,
        "cross_domains": cross_domains,
        "definition": definition,
        "observable_cues": observable_cues,
        "key_parameters": key_parameters,
        "related_mf_ids": related_mf_ids,
        "example_l0_statements": [s(ref_domain, ref_idx) for ref_domain, ref_idx in refs],
        "granularity_note": granularity_note,
    }


PHENOMENA = [
    phn(
        "egg_protein_setting",
        "Egg Protein Setting",
        "蛋羹起身",
        "protein_science",
        ["thermal_dynamics", "texture_rheology"],
        "Heating denatures egg proteins and turns a free-flowing mixture into a spoonable or sliceable gel. The kitchen signal is the shift from runny to softly set, then fully coagulated.",
        ["蛋液变稠", "表面定住", "舀起时能挂勺或成块"],
        ["core temperature", "heating time", "water-to-egg ratio"],
        ["MF-T03", "MF-C05"],
        [("protein_science", 1), ("protein_science", 3)],
        "This is a chef-manageable setting window that bundles multiple protein denaturation facts into one observable doneness outcome.",
    ),
    phn(
        "gluten_overdevelopment",
        "Gluten Overdevelopment",
        "面团打老了",
        "protein_science",
        ["carbohydrate", "texture_rheology"],
        "Mechanical work aligns and tightens gluten-forming proteins until dough becomes too elastic and difficult to shape. The useful boundary is the point where extensibility gives way to snap-back.",
        ["面团回缩", "擀开后又缩回去", "手感发紧发硬"],
        ["mixing time", "hydration", "rest time"],
        ["MF-R01", "MF-T03"],
        [("protein_science", 2), ("protein_science", 4)],
        "This captures the operational transition from workable dough to overworked dough, which is more useful than treating each protein fact separately.",
    ),
    phn(
        "sugar_inversion_syrup",
        "Sugar Inversion Syrup",
        "熬糖转化",
        "carbohydrate",
        ["thermal_dynamics", "maillard_caramelization"],
        "Boiling sucrose in water can split it into glucose and fructose, changing sweetness, viscosity, and crystallization behavior. Cooks notice it as syrup that stays smoother and is less eager to grain up.",
        ["糖浆更顺", "不容易返砂", "甜感更圆"],
        ["boiling temperature", "water ratio", "heating time"],
        ["MF-T03", "MF-M06"],
        [("carbohydrate", 2), ("carbohydrate", 4), ("carbohydrate", 8)],
        "This groups hydrolysis-driven syrup behavior into one candy-making control point rather than isolated sugar identity facts.",
    ),
    phn(
        "pectin_jam_set",
        "Pectin Jam Set",
        "果酱起胶",
        "carbohydrate",
        ["salt_acid_chemistry", "texture_rheology", "water_activity"],
        "Pectin forms a stable jam network only inside a fairly narrow acid-sugar-solids window. The cook sees it as the point where a loose fruit boil suddenly starts to sheet and hold.",
        ["果酱开始挂勺", "冷却后能成胶", "稀浆变得有支撑"],
        ["pH", "sugar concentration", "pectin concentration"],
        ["MF-M04", "MF-R04"],
        [("carbohydrate", 9), ("carbohydrate", 3), ("carbohydrate", 5)],
        "This is the classic jam-setting window: broader than any single formulation fact, but narrower than the whole carbohydrate domain.",
    ),
    phn(
        "starch_body_build",
        "Starch Body Build",
        "淀粉出稠感",
        "carbohydrate",
        ["texture_rheology", "water_activity"],
        "Amylose, amylopectin, and soluble polysaccharides build thickness and creamy body in starch-rich foods. In the kitchen this reads as whether a puree, porridge, or corn preparation feels thin, creamy, or pasty.",
        ["入口更绵", "稠度起来", "口感从水变糯"],
        ["amylose-to-amylopectin ratio", "soluble polysaccharide level", "water content"],
        ["MF-R04", "MF-R05"],
        [("carbohydrate", 6), ("carbohydrate", 7), ("carbohydrate", 10)],
        "This is the texture-building behavior cooks actually manage when choosing starch type and water level.",
    ),
    phn(
        "cloudy_broth_emulsification",
        "Cloudy Broth Emulsification",
        "奶白汤",
        "lipid_science",
        ["mass_transfer", "texture_rheology"],
        "Boiling turbulence and shear break fat into small droplets that stay suspended in the liquid phase. The visible cue is stock turning milky instead of remaining clear.",
        ["汤色变奶白", "表面油珠变细", "口感更厚"],
        ["boil intensity", "shear rate", "fat loading"],
        ["MF-C03", "MF-C01"],
        [("lipid_science", 1), ("lipid_science", 2)],
        "This combines the droplet-formation and suspension behavior that chefs use to decide whether a broth should run clear or creamy-white.",
    ),
    phn(
        "fat_melt_window",
        "Fat Melt Window",
        "油脂化口",
        "lipid_science",
        ["thermal_dynamics", "texture_rheology"],
        "Different fatty acid mixes melt across different temperature windows, so some fats soften in the mouth while others stay waxy. This is experienced directly as spreadability, mouth-coating, and melt-away speed.",
        ["室温软硬不同", "入口化得快或慢", "口腔里发蜡或发润"],
        ["fatty acid profile", "temperature", "solid fat fraction"],
        ["MF-T03", "MF-R03"],
        [("lipid_science", 3), ("lipid_science", 5), ("lipid_science", 6)],
        "This is the practical melting profile cooks feel and manipulate, not just a list of lipid composition facts.",
    ),
    phn(
        "cocoa_butter_temper_set",
        "Cocoa Butter Temper Set",
        "巧克力调温定型",
        "lipid_science",
        ["texture_rheology", "thermal_dynamics"],
        "Cocoa butter can crystallize into several forms, but only a narrow tempering path gives good gloss, snap, and bloom resistance. The chef sees it in shine, clean break, and whether the surface later turns dull.",
        ["表面发亮", "掰开有脆响", "放一会儿不泛白"],
        ["cooling curve", "seed crystal control", "shear during tempering"],
        ["MF-R03", "MF-T03"],
        [("lipid_science", 4), ("lipid_science", 10), ("lipid_science", 5)],
        "This is the operational chocolate-tempering outcome that sits above single crystal facts and below the whole lipid-science domain.",
    ),
    phn(
        "yeast_gas_lift",
        "Yeast Gas Lift",
        "发起来了",
        "fermentation",
        ["mass_transfer", "texture_rheology"],
        "Under low-oxygen conditions yeast converts sugars into ethanol and carbon dioxide, inflating doughs and mash. What cooks track is whether the system is rising, bubbling, and developing fermentation aroma on schedule.",
        ["面团鼓起来", "气泡增多", "有酒香或发酵香"],
        ["temperature", "sugar availability", "oxygen level"],
        ["MF-K05"],
        [("fermentation", 2), ("fermentation", 3), ("fermentation", 4)],
        "This captures the working fermentation behavior of yeast rather than isolated biochemical equations.",
    ),
    phn(
        "yogurt_sour_set",
        "Yogurt Sour Set",
        "酸奶起凝",
        "fermentation",
        ["salt_acid_chemistry", "protein_science"],
        "Thermophilic starter cultures acidify milk until dairy proteins form a soft gel. The useful kitchen endpoint is the combination of tang, thickness, and clean milk gel rather than microbial identity alone.",
        ["奶液变稠", "出现酸香", "表面能完整凝住"],
        ["incubation temperature", "starter culture balance", "fermentation time"],
        ["MF-K05", "MF-M04"],
        [("fermentation", 5), ("fermentation", 9), ("fermentation", 10)],
        "This is the everyday yogurt-making set point chefs manage, bundling culture choice, temperature, and acid development together.",
    ),
    phn(
        "double_fermentation_acid_rise",
        "Double Fermentation Acid Rise",
        "双发酵走酸",
        "fermentation",
        ["salt_acid_chemistry", "food_safety"],
        "Some fermented products first build alcohol and then convert that alcohol into acid, driving a steady drop in pH. In practice this shows up as a shift from sweet or fruity notes toward sharper sourness.",
        ["闻起来越来越酸", "pH往下走", "酒香转醋香"],
        ["temperature", "time", "substrate sugar and alcohol level"],
        ["MF-K05", "MF-M04"],
        [("fermentation", 1), ("fermentation", 2), ("fermentation", 7)],
        "This describes the observable souring trajectory across linked fermentation stages, which is a tighter kitchen unit than the entire fermentation domain.",
    ),
    phn(
        "danger_zone_bloom",
        "Danger Zone Bloom",
        "危险温区暴长",
        "food_safety",
        ["fermentation", "thermal_dynamics"],
        "Microbes multiply fastest when food sits in the classic danger zone, especially around warm holding temperatures. Cooks manage this as a time-temperature exposure problem rather than a single kill step.",
        ["放久了风险陡增", "温热状态最危险", "回温慢的菜更不安心"],
        ["holding temperature", "time in zone", "oxygen and acidity conditions"],
        ["MF-K05"],
        [("food_safety", 4), ("food_safety", 6), ("food_safety", 9)],
        "This is the operational growth-risk window behind many service mistakes, broader than one organism fact but narrower than all food safety.",
    ),
    phn(
        "thermal_log_kill",
        "Thermal Log Kill",
        "巴杀到位",
        "food_safety",
        ["protein_science", "thermal_dynamics"],
        "Heat kills microbes in predictable log reductions rather than in an all-or-nothing jump. The practical question is whether the product has spent enough time at temperature to hit the target reduction.",
        ["加热后风险明显下降", "不是一瞬间全灭", "时间不够就不稳"],
        ["process temperature", "hold time", "initial microbial load"],
        ["MF-K02", "MF-K04"],
        [("food_safety", 2), ("food_safety", 7), ("food_safety", 9)],
        "This is the core pasteurization control unit that chefs and processors actually work with.",
    ),
    phn(
        "pressure_spore_kill",
        "Pressure Spore Kill",
        "压力灭芽孢",
        "food_safety",
        ["thermal_dynamics", "salt_acid_chemistry"],
        "Heat-resistant spores need both higher temperatures and enough integrated lethality to become safe. In kitchen terms this is why pressure conditions matter for low-acid, anaerobic foods where ordinary boiling is not enough.",
        ["普通煮沸不放心", "必须上压力", "低酸密封食品风险更高"],
        ["process temperature", "pressure", "product acidity"],
        ["MF-K02", "MF-K03", "MF-K04"],
        [("food_safety", 3), ("food_safety", 4), ("food_safety", 6)],
        "This phenomenon groups the spore-control regime that matters for pressure canning and similar high-risk preparations.",
    ),
    phn(
        "freezing_parasite_control",
        "Freezing Parasite Control",
        "冷冻灭寄生虫",
        "food_safety",
        ["thermal_dynamics"],
        "For some raw fish and meats, safety comes from holding low enough freezing temperatures long enough to inactivate parasites. The controllable kitchen signal is a validated temperature-time freezing schedule, not just 'it felt frozen.'",
        ["冷冻有明确时长门槛", "生食前要走足冷冻程序", "不是随便冻一下就行"],
        ["freezer temperature", "hold duration", "product thickness"],
        ["MF-T05", "MF-K02"],
        [("food_safety", 5), ("food_safety", 10)],
        "This is a distinct safety pathway with its own schedule logic, so it deserves its own phenomenon rather than being merged into generic microbial kill.",
    ),
    phn(
        "crisp_shell_rehydration",
        "Crisp Shell Rehydration",
        "脆壳回潮",
        "water_activity",
        ["mass_transfer", "texture_rheology"],
        "Water migrates from wetter layers into dry crisp layers until textures equalize. Cooks experience it as caramel shells, tuile-like sheets, or cookies losing their snap after sitting.",
        ["脆壳发软", "咬口不再清脆", "表层吸潮塌下去"],
        ["water activity gradient", "holding time", "ambient humidity"],
        ["MF-M01", "MF-M02", "MF-R05"],
        [("water_activity", 1), ("water_activity", 5), ("water_activity", 8)],
        "This directly captures the common kitchen failure where structure is lost because moisture equilibrates across layers.",
    ),
    phn(
        "hygroscopic_caking",
        "Hygroscopic Caking",
        "返潮结块",
        "water_activity",
        ["mass_transfer", "salt_acid_chemistry"],
        "Some dry ingredients actively pull water from air, so powders stop flowing and begin to clump. The observable issue is storage stability: what poured freely yesterday may cake today.",
        ["粉末结块", "表面发潮", "倒不顺、筛不开"],
        ["ambient humidity", "solute hygroscopicity", "package seal quality"],
        ["MF-M02", "MF-M03"],
        [("water_activity", 2), ("water_activity", 3), ("water_activity", 6)],
        "This is the practical moisture-pickup behavior behind many pantry stability problems.",
    ),
    phn(
        "free_water_risk_band",
        "Free Water Risk Band",
        "自由水偏高",
        "water_activity",
        ["food_safety", "mass_transfer"],
        "High-aw foods behave very differently from dry foods because microbes and water-driven changes become possible only when enough free water is present. In practice this decides whether a product is shelf-stable, chilled, or highly perishable.",
        ["高水活度更容易坏", "低水活度更耐放", "看着湿润的食品风险更高"],
        ["water activity", "solute concentration", "storage temperature"],
        ["MF-M02", "MF-M01"],
        [("water_activity", 4), ("water_activity", 7), ("water_activity", 9)],
        "This pulls together the usable shelf-life threshold logic that chefs care about when moving between wet and dry product formats.",
    ),
    phn(
        "enzymatic_cut_browning",
        "Enzymatic Cut Browning",
        "切面发褐",
        "enzyme",
        ["color_pigment", "oxidation_reduction"],
        "Polyphenol oxidase and oxygen darken cut produce unless the enzyme is inactivated quickly enough. The visible cue is the fresh cut surface turning tan or brown while the interior was originally pale.",
        ["切开后很快变色", "表面由浅变褐", "焯过后明显更稳"],
        ["enzyme inactivation temperature", "hold time", "oxygen exposure"],
        ["MF-K01", "MF-T03"],
        [("enzyme", 2), ("enzyme", 3), ("enzyme", 8)],
        "This is a classic chef-observable enzyme window with a clear visual outcome and a calculable thermal inactivation entry point.",
    ),
    phn(
        "enzymatic_filling_thinning",
        "Enzymatic Filling Thinning",
        "馅料返稀",
        "enzyme",
        ["carbohydrate", "texture_rheology"],
        "Residual starch-degrading or sugar-splitting enzymes keep working after mixing or partial cooking, so fillings and centers can thin or liquefy over time. The kitchen signal is a mixture that looked stable, then loosens unexpectedly.",
        ["本来很稠后来变稀", "馅心流动性增强", "甜心或奶馅慢慢化开"],
        ["enzyme survival", "substrate concentration", "post-cook holding time"],
        ["MF-K01", "MF-T03"],
        [("enzyme", 1), ("enzyme", 6), ("enzyme", 7)],
        "This groups several enzyme carryover problems into one controllable kitchen failure mode.",
    ),
    phn(
        "shellfish_red_reveal",
        "Shellfish Red Reveal",
        "虾蟹返红",
        "color_pigment",
        ["protein_science", "thermal_dynamics"],
        "Heat releases carotenoid pigments from their protein-bound state in crustaceans, making shells and flesh turn vivid orange-red. Cooks use this as a direct doneness cue.",
        ["颜色从灰青转橙红", "熟色突然跳出来", "壳和肉都更鲜艳"],
        ["surface temperature", "heating time", "pigment-protein binding state"],
        ["MF-T03"],
        [("color_pigment", 2), ("color_pigment", 4)],
        "This is a tight, highly observable cooking-color transition rather than a generic pigment taxonomy.",
    ),
    phn(
        "acid_driven_color_fade",
        "Acid-Driven Color Fade",
        "酸一上去就褪色",
        "color_pigment",
        ["salt_acid_chemistry", "oxidation_reduction"],
        "Acid can directly shift or lighten some food colors, especially where pigment form is pH-sensitive or where brown pigments become less intense. The working cue is a sauce, fruit, or garnish changing tone as acid is added.",
        ["颜色变浅", "红紫色调偏移", "加酸后卖相突然不同"],
        ["pH", "acid type", "pigment concentration"],
        ["MF-M04"],
        [("color_pigment", 1), ("color_pigment", 3), ("color_pigment", 9)],
        "This is a real kitchen color-control handle, narrower than all pigment chemistry but broader than one compound description.",
    ),
    phn(
        "natural_pigment_retention",
        "Natural Pigment Retention",
        "本色留得住",
        "color_pigment",
        ["thermal_dynamics", "oxidation_reduction"],
        "Whether foods stay vividly green, golden, or red depends on how well native pigments survive growth, harvest, and cooking conditions. Chefs experience it as some ingredients holding brilliant color while others wash out fast.",
        ["绿色更鲜", "黄油更金", "红色更稳不发灰"],
        ["temperature exposure", "pigment load", "harvest and storage conditions"],
        ["MF-T03"],
        [("color_pigment", 5), ("color_pigment", 8), ("color_pigment", 10)],
        "This phenomenon groups the retention of natural display color into one usable quality outcome.",
    ),
    phn(
        "vacuum_gentle_concentration",
        "Vacuum Gentle Concentration",
        "低温收香",
        "equipment_physics",
        ["thermal_dynamics", "aroma_volatiles"],
        "Vacuum lowers boiling conditions while rotation spreads liquid into a thin film, so concentration can happen at gentler temperatures. The kitchen payoff is faster reduction with less cooked-off aroma damage.",
        ["更低温就能蒸发", "收浓更快", "香气不容易煮老"],
        ["pressure level", "bath temperature", "rotation speed"],
        ["MF-M03", "MF-T04"],
        [("equipment_physics", 1), ("equipment_physics", 6), ("equipment_physics", 7)],
        "This is a concrete device-enabled concentration behavior with visible and aromatic consequences.",
    ),
    phn(
        "microwave_internal_heating",
        "Microwave Internal Heating",
        "微波里外一起热",
        "equipment_physics",
        ["thermal_dynamics", "water_activity"],
        "Microwave energy couples with food at a characteristic frequency and can heat beyond the surface-dominated pattern of pans and ovens. The practical signal is rapid heating that seems to build from within the food mass.",
        ["升温很快", "不只表面热", "中心和表面升温路径不同于炒煎"],
        ["microwave frequency", "product geometry", "water content"],
        ["MF-T01", "MF-T02"],
        [("equipment_physics", 5), ("equipment_physics", 9)],
        "This is a distinct equipment-driven heating mode that belongs between raw microwave specs and the whole equipment domain.",
    ),
    phn(
        "seared_maillard_browning",
        "Seared Maillard Browning",
        "煎香上色",
        "maillard_caramelization",
        ["protein_science", "aroma_volatiles", "thermal_dynamics"],
        "Once a surface reaches roughly the Maillard-active range and has both amino groups and reducing sugars available, browned aromas and pigments develop quickly. Cooks read this as the moment food starts smelling roasted and looking deeply golden-brown.",
        ["表面上色", "出现煎香烤香", "锅里开始有焦香复合味"],
        ["surface temperature", "time above threshold", "reducing sugar availability"],
        ["MF-T03", "MF-C05"],
        [("maillard_caramelization", 2), ("maillard_caramelization", 3), ("maillard_caramelization", 4)],
        "This is the everyday browning window chefs manage on pans, grills, and ovens.",
    ),
    phn(
        "caramel_shell_snap",
        "Caramel Shell Snap",
        "糖壳起脆",
        "maillard_caramelization",
        ["carbohydrate", "texture_rheology"],
        "Sugars can melt, caramelize, and then harden into a thin brittle glass on cooling. The relevant kitchen effect is the formation of a shiny shell that breaks cleanly instead of staying tacky.",
        ["冷却后形成硬脆壳", "敲开有脆裂感", "过火时会发苦"],
        ["sugar type", "peak temperature", "cooling rate"],
        ["MF-T03", "MF-R04"],
        [("maillard_caramelization", 1), ("maillard_caramelization", 5), ("maillard_caramelization", 6)],
        "This groups caramel melt-set behavior into one pastry and candy control point.",
    ),
    phn(
        "black_garlic_slow_browning",
        "Black Garlic Slow Browning",
        "黑蒜养熟",
        "maillard_caramelization",
        ["water_activity", "aroma_volatiles"],
        "Warm, humid holding over long periods drives unusually slow Maillard development that deepens both color and savory-sweet aroma. The chef sees gradual darkening and mellowing rather than a fast sear reaction.",
        ["颜色慢慢变深", "蒜辣感变柔", "甜香和酱香上来"],
        ["holding temperature", "relative humidity", "aging duration"],
        ["MF-T03", "MF-C05"],
        [("maillard_caramelization", 2), ("maillard_caramelization", 9), ("maillard_caramelization", 10)],
        "This is a recognizable long-cycle browning regime with its own sensory profile and control parameters.",
    ),
    phn(
        "wok_patina_blackening",
        "Wok Patina Blackening",
        "开锅养锅",
        "oxidation_reduction",
        ["equipment_physics", "thermal_dynamics"],
        "Seasoning a wok involves controlled oxidation that forms a stable black surface instead of flaky red rust. Cooks notice it as the pan turning darker, smoother, and better behaved during stir-frying.",
        ["锅面由灰转黑", "表面更顺", "不再像生铁那样发涩"],
        ["surface temperature", "oxygen exposure", "metal surface condition"],
        ["MF-T03"],
        [("oxidation_reduction", 2), ("oxidation_reduction", 3), ("oxidation_reduction", 8)],
        "This is a practical cookware-conditioning phenomenon, not just a general redox statement.",
    ),
    phn(
        "warm_oil_rancidity_chain",
        "Warm Oil Rancidity Chain",
        "哈喇味上来",
        "oxidation_reduction",
        ["lipid_science", "aroma_volatiles"],
        "Unsaturated fats can enter self-propagating radical oxidation, especially once protective components are depleted by heat. The sensory result is stale, painty, or rancid notes in warmed fats and fried foods.",
        ["出现哈喇味", "油香变钝发旧", "回味发苦发败"],
        ["heating temperature", "oxygen exposure", "degree of unsaturation"],
        ["MF-T03"],
        [("oxidation_reduction", 5), ("oxidation_reduction", 6), ("oxidation_reduction", 10)],
        "This is the kitchen-relevant oxidation cascade behind deteriorating frying oils and stored fats.",
    ),
    phn(
        "antioxidant_shielding",
        "Antioxidant Shielding",
        "香草护油",
        "oxidation_reduction",
        ["lipid_science", "aroma_volatiles"],
        "Phenolic antioxidants and reducing compounds can intercept radicals and slow flavor-damaging oxidation. In practice this reads as herbs, acids, or antioxidant-rich ingredients helping oils and aromatics stay fresher longer.",
        ["香味保持更久", "油不那么快发旧", "颜色和气味衰退变慢"],
        ["antioxidant load", "exposure to heat", "oxygen contact"],
        ["MF-T03"],
        [("oxidation_reduction", 1), ("oxidation_reduction", 7), ("oxidation_reduction", 9)],
        "This is a chef-usable protection pattern that links ingredient choice to oxidative stability.",
    ),
    phn(
        "pickle_brine_balance",
        "Pickle Brine Balance",
        "酸咸腌透",
        "salt_acid_chemistry",
        ["food_safety", "mass_transfer"],
        "Salt and acid work together to shape flavor, preservation, and texture in pickled foods. Cooks experience this as the balance point where a brine tastes bright and penetrates without becoming harsh or flat.",
        ["酸咸更协调", "腌味进得更快", "成品更爽利也更稳"],
        ["salt concentration", "pH", "pickling temperature"],
        ["MF-M04"],
        [("salt_acid_chemistry", 2), ("salt_acid_chemistry", 6), ("salt_acid_chemistry", 9)],
        "This is the operational brine window cooks manage, not just a set of pH facts.",
    ),
    phn(
        "chemical_leavening_lift",
        "Chemical Leavening Lift",
        "一遇酸就起发",
        "salt_acid_chemistry",
        ["texture_rheology", "carbohydrate"],
        "Baking powders and related systems release carbon dioxide when acid-base conditions line up, creating lift in doughs and batters. The cook sees this as batter foaming, cakes opening, and crumb getting lighter.",
        ["面糊起泡", "烤后更松", "内部组织更蓬"],
        ["acid-base balance", "available CO2 yield", "mixing and bake timing"],
        ["MF-M04"],
        [("salt_acid_chemistry", 2), ("salt_acid_chemistry", 7), ("salt_acid_chemistry", 9)],
        "This groups the practical lift behavior of chemical leavening into one phenomenon chefs and bakers can tune.",
    ),
    phn(
        "egg_white_alkaline_drift",
        "Egg White Alkaline Drift",
        "老蛋清发碱",
        "salt_acid_chemistry",
        ["protein_science", "taste_perception"],
        "As eggs age, albumen pH drifts upward and changes the way whites whip, set, and taste. In the kitchen this shows up as old whites behaving differently from fresh ones even before you cook them.",
        ["蛋清闻着更碱", "打发和凝固表现变了", "新老蛋做法手感不一样"],
        ["storage time", "albumen pH", "starting freshness"],
        ["MF-M04"],
        [("salt_acid_chemistry", 3), ("salt_acid_chemistry", 8), ("salt_acid_chemistry", 10)],
        "This is a narrow but real kitchen quality shift driven by pH drift rather than by all acid-base chemistry.",
    ),
    phn(
        "temperature_boosted_flavor",
        "Temperature Boosted Flavor",
        "热着更有味",
        "taste_perception",
        ["thermal_dynamics", "texture_rheology"],
        "Serving temperature changes both taste intensity and texture perception, so the same seasoning can feel dull when cold and fuller when warm. Chefs use this constantly when adjusting soups, sauces, and desserts.",
        ["热的时候味道更开", "冷了显得淡", "温度一变口感和味感一起变"],
        ["serving temperature", "base taste intensity", "matrix texture"],
        ["MF-R06"],
        [("taste_perception", 1), ("taste_perception", 3), ("taste_perception", 7)],
        "This is a direct sensory control lever in service, broader than one receptor fact but smaller than the whole perception domain.",
    ),
    phn(
        "sourness_channel_hit",
        "Sourness Channel Hit",
        "酸味顶舌",
        "taste_perception",
        ["salt_acid_chemistry"],
        "Sour taste emerges when acids alter proton flow at taste-cell membranes, producing a sharp and immediate signal. In use, cooks notice how small pH shifts can make a dish suddenly feel brighter or harsher.",
        ["入口更尖更亮", "口水感增强", "酸度一点点变化就很明显"],
        ["pH", "acid identity", "serving temperature"],
        ["MF-R06", "MF-M04"],
        [("taste_perception", 2), ("taste_perception", 4), ("taste_perception", 5)],
        "This is the actionable sourness response window chefs tune with acid additions.",
    ),
    phn(
        "umami_glutamate_hit",
        "Umami Glutamate Hit",
        "鲜味顶上来",
        "taste_perception",
        ["aroma_volatiles"],
        "Glutamate produces a distinct savory taste quality rather than just a stronger version of saltiness. The practical signal is broth or seasoning suddenly feeling deeper and more mouth-filling.",
        ["汤头更厚更鲜", "尾味更长", "不是咸而是鲜"],
        ["glutamate concentration", "serving temperature", "overall taste matrix"],
        ["MF-R06"],
        [("taste_perception", 8), ("taste_perception", 9), ("taste_perception", 10)],
        "This is a chef-recognizable flavor event with clear culinary leverage, not just a history-of-science fact.",
    ),
    phn(
        "retronasal_aroma_bloom",
        "Retronasal Aroma Bloom",
        "入口后返香",
        "aroma_volatiles",
        ["taste_perception", "mass_transfer"],
        "A large share of flavor is perceived when volatiles released in the mouth travel up to the nose during chewing and swallowing. Cooks recognize it when a dish seems to open after it is already in the mouth.",
        ["刚入口还好、咽下后更香", "回香明显", "咀嚼时香气越吃越开"],
        ["volatile release rate", "airflow during eating", "food temperature"],
        ["MF-M03", "MF-M05", "MF-M01"],
        [("aroma_volatiles", 1), ("aroma_volatiles", 5), ("aroma_volatiles", 6)],
        "This is a clear sensory event in eating, making it a natural mid-level phenomenon for the graph.",
    ),
    phn(
        "aroma_resting_roundness",
        "Aroma Resting Roundness",
        "回香养熟",
        "aroma_volatiles",
        ["thermal_dynamics", "oxidation_reduction"],
        "Cooling and resting can change how volatile compounds partition and recombine, sometimes making aroma feel rounder and more integrated. The kitchen sign is that a product smells better after a short rest than right at peak heat.",
        ["放一会儿更香", "香气更圆不尖", "前后闻起来层次不同"],
        ["rest time", "cooling rate", "volatile composition"],
        ["MF-M03", "MF-M05"],
        [("aroma_volatiles", 4), ("aroma_volatiles", 9), ("aroma_volatiles", 10)],
        "This captures the familiar 'rest then smell again' improvement that cooks use in tasting and finishing.",
    ),
    phn(
        "peak_to_nose_gap",
        "Peak-to-Nose Gap",
        "闻起来不等于峰高",
        "aroma_volatiles",
        ["taste_perception", "equipment_physics"],
        "Instrument intensity and perceived aroma intensity do not line up neatly because receptor response and airflow matter too. The kitchen lesson is that a dish can read stronger or weaker than its analytical profile suggests.",
        ["闻起来并不完全按仪器说话", "有些香很冲但峰不高", "气流一变香感也变"],
        ["headspace partitioning", "airflow", "receptor sensitivity"],
        ["MF-M05", "MF-M01"],
        [("aroma_volatiles", 2), ("aroma_volatiles", 3), ("aroma_volatiles", 7)],
        "This is a practical sensory mismatch phenomenon that matters when translating analysis into cooking decisions.",
    ),
    phn(
        "altitude_boil_drop",
        "Altitude Boil Drop",
        "高处难煮透",
        "thermal_dynamics",
        ["water_activity", "equipment_physics"],
        "As pressure falls with altitude, boiling temperature drops and wet cooking becomes less thermally aggressive. The cook notices this as longer simmering and slower softening at a rolling boil that looks normal.",
        ["同样沸腾却煮得更慢", "炖煮更拖时间", "高海拔更难把食材煮透"],
        ["ambient pressure", "boiling point", "product size"],
        ["MF-T04", "MF-M06"],
        [("thermal_dynamics", 1), ("thermal_dynamics", 5), ("thermal_dynamics", 6)],
        "This is a classic kitchen-scale pressure-to-boiling phenomenon, much tighter than the whole heat-transfer domain.",
    ),
    phn(
        "surface_core_heat_gap",
        "Surface-Core Heat Gap",
        "外熟里生",
        "thermal_dynamics",
        ["equipment_physics", "protein_science"],
        "Pan and oven cooking run on a two-stage heat path: first heat reaches the surface, then it conducts toward the center. The observable outcome is a surface that looks done while the core still lags behind.",
        ["表面已经上色", "中心还没到位", "薄厚不同熟得差很多"],
        ["surface heat transfer coefficient", "thickness", "thermal diffusivity"],
        ["MF-T01", "MF-T04", "MF-T02"],
        [("thermal_dynamics", 2), ("thermal_dynamics", 9)],
        "This is the practical doneness gap chefs manage every time they balance crust against center temperature.",
    ),
    phn(
        "freeze_cell_shatter",
        "Freeze Cell Shatter",
        "冻伤出水",
        "thermal_dynamics",
        ["mass_transfer", "texture_rheology"],
        "Freezing can grow ice crystals large enough to puncture cell walls, so thawed produce leaks and softens. Cooks recognize it as drip loss and collapsed texture after freezing.",
        ["解冻后冒水", "组织发糟", "口感不再脆挺"],
        ["freezing rate", "crystal size", "storage temperature"],
        ["MF-T05", "MF-T01"],
        [("thermal_dynamics", 3), ("thermal_dynamics", 4)],
        "This is a distinct freeze-damage outcome that chefs can see and feel immediately after thawing.",
    ),
    phn(
        "brine_diffusion_uptake",
        "Brine Diffusion Uptake",
        "腌进去",
        "mass_transfer",
        ["salt_acid_chemistry", "water_activity"],
        "Salt and water move along concentration gradients during brining until the food approaches a new equilibrium. The practical question is how fast seasoning penetrates and how much weight the product should gain.",
        ["外面有味里面没味会逐步改善", "重量增加", "咸度慢慢往里走"],
        ["brine concentration", "time", "target pickup weight"],
        ["MF-M01"],
        [("mass_transfer", 7), ("mass_transfer", 8), ("mass_transfer", 9)],
        "This is the operative curing and brining process cooks manage, not just the general idea of diffusion.",
    ),
    phn(
        "drying_flavor_concentration",
        "Drying Flavor Concentration",
        "越干越鲜",
        "mass_transfer",
        ["water_activity", "taste_perception"],
        "As water leaves a food, dissolved taste compounds become more concentrated and flavor intensity rises. The cook reads it as dried ingredients tasting denser, sweeter, saltier, or more savory than their fresh versions.",
        ["风味更集中", "鲜味更顶", "同样一口更有劲"],
        ["water loss", "drying rate", "initial solute load"],
        ["MF-M01", "MF-M02"],
        [("mass_transfer", 6), ("mass_transfer", 7), ("mass_transfer", 8)],
        "This groups the sensory payoff of drying into one usable kitchen phenomenon.",
    ),
    phn(
        "thin_layer_freeze_drying",
        "Thin-Layer Freeze Drying",
        "冻干起得快",
        "mass_transfer",
        ["thermal_dynamics", "equipment_physics"],
        "Freeze-drying speeds up when material is frozen into thinner, higher-surface-area forms that sublimate more easily under vacuum. The practical sign is shorter drying time for finely spread or ground frozen product.",
        ["铺薄后干得更快", "研碎后冻干提速", "真空升华更顺"],
        ["surface area", "layer thickness", "vacuum level"],
        ["MF-M01", "MF-M06"],
        [("mass_transfer", 1), ("mass_transfer", 3), ("mass_transfer", 10)],
        "This is a real process-scale transfer behavior with immediate design implications for drying operations.",
    ),
    phn(
        "heat_stable_gel_set",
        "Heat-Stable Gel Set",
        "凝胶成型",
        "texture_rheology",
        ["water_activity", "thermal_dynamics"],
        "Some gel systems set at one temperature and melt only much later, or form a skin and body by ionic crosslinking. Cooks experience this as a gel that can plate cleanly and survive warmer service without collapsing right away.",
        ["冷却后能定型", "端上桌不容易塌", "表皮和内部会形成明显结构"],
        ["set temperature", "crosslinking ion level", "service temperature"],
        ["MF-R04", "MF-R05"],
        [("texture_rheology", 1), ("texture_rheology", 10)],
        "This phenomenon joins several gel-formation facts into one chef-visible forming and holding behavior.",
    ),
    phn(
        "particle_size_body_shift",
        "Particle Size Body Shift",
        "粗细决定口感",
        "texture_rheology",
        ["carbohydrate", "lipid_science"],
        "Particle size changes how a food flows and feels, so the same ingredient family can eat creamy, gritty, or heavy depending on grind. In the kitchen this shows up immediately in body and smoothness.",
        ["更细更滑", "更粗更砂更糙", "研磨变化会改稠度"],
        ["particle size", "grinding intensity", "solid loading"],
        ["MF-R01", "MF-C01"],
        [("texture_rheology", 2), ("texture_rheology", 4), ("texture_rheology", 6)],
        "This is the practical mouthfeel consequence of particle engineering, which is exactly the right middle layer for chefs.",
    ),
    phn(
        "yield_stress_sauce_flow",
        "Yield-Stress Sauce Flow",
        "稠到会挂勺",
        "texture_rheology",
        ["lipid_science"],
        "Some sauces and suspensions do not flow until enough force is applied, then move with a distinctive thickness profile. Cooks see this as mixtures that sit still in the bowl but loosen when stirred or poured.",
        ["静置时不怎么流", "搅一搅才动", "能挂勺、能包裹食材"],
        ["yield stress", "apparent viscosity", "shear rate"],
        ["MF-R01", "MF-R02", "MF-R03"],
        [("texture_rheology", 3), ("texture_rheology", 6), ("texture_rheology", 7)],
        "This is a highly actionable flow behavior that sits cleanly between raw rheology equations and whole-texture discussions.",
    ),
    phn(
        "texture_firming_window",
        "Texture Firming Window",
        "咬劲定住了",
        "texture_rheology",
        ["thermal_dynamics", "taste_perception"],
        "Some plant tissues become more resistant to later over-softening when briefly held in a narrow warm preheating range. The kitchen payoff is vegetables or fruits that keep bite through longer cooking.",
        ["先预热后更耐煮", "久煮也还留点脆或挺", "剪切时更有阻力"],
        ["preheat temperature", "preheat time", "final cook severity"],
        ["MF-R07", "MF-R06"],
        [("texture_rheology", 5), ("texture_rheology", 9)],
        "This is a precise, chef-observable firmness window, not just a generic statement that texture changes with cooking.",
    ),
]


def validate(phenomena):
    assert 50 <= len(phenomena) <= 80, len(phenomena)
    counts = {}
    seen_ids = set()
    source_statements = {
        item["statement"]
        for items in DOMAINS.values()
        for item in items
    }
    for item in phenomena:
        assert item["phn_id"] not in seen_ids, item["phn_id"]
        seen_ids.add(item["phn_id"])
        counts[item["domain"]] = counts.get(item["domain"], 0) + 1
        for mf_id in item["related_mf_ids"]:
            assert mf_id in VALID_MF_IDS, mf_id
        assert 2 <= len(item["example_l0_statements"]) <= 3, item["phn_id"]
        for stmt in item["example_l0_statements"]:
            assert stmt in source_statements, stmt
    assert len(counts) == 17, counts
    for domain, count in counts.items():
        assert 2 <= count <= 4, (domain, count)


def main():
    validate(PHENOMENA)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("w", encoding="utf-8") as fh:
        json.dump(PHENOMENA, fh, ensure_ascii=False, indent=2)
    print(f"Wrote {len(PHENOMENA)} phenomena to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
